# Generated by Django 2.2 on 2020-09-28 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject1', models.CharField(max_length=100)),
                ('subject2', models.CharField(max_length=100)),
                ('subject3', models.CharField(max_length=100)),
                ('subject4', models.CharField(max_length=100)),
                ('subject5', models.CharField(max_length=100)),
                ('subject6', models.CharField(max_length=100)),
            ],
        ),
    ]
